version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - cd target
      - zip -r ../deployment_package.zip DemoSpringProject-0.0.1-SNAPSHOT.jar
      - cd ..	  
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - aws lambda update-function-code --function-name DemoSpringappLambda --zip-file fileb://target/DemoSpringProject-0.0.1-SNAPSHOT.jar
artifacts:
  files:
  - appspec.yml  
  - deployment_package.zip
# - /tmp/opt/.m2/repository/com/example/DemoSpringProject/0.0.1-SNAPSHOT/DemoSpringProject-0.0.1-SNAPSHOT.jar
# - '**/*'
# - .ebextensions/**/*
